version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(ruby)"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ruby"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
