# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Making Life Easier
email: rlc@vlinder.ca
description: >- # this means to ignore newlines until "baseurl:"
    The blog of a vereran C++ developer working in SCADA and industrial embedded devices, focusing 
    on security and communications.
#    Ronald Landheer-Cieslak is the founder of Vlinder Software and co-founder of Optimus Analysis.
#    He is a veteran developer in C++ and has worked in SCADA systems for the last decade.
#    Specializing in communications and security, his research and development activities focus on
#    industrial embedded devices. He has lead development teams in developing several products, 
#    providing both technical guidance and managing the technical aspects of those projects.
#    
#    Ronald is a member of the IEEE, the ACM and the IANA. He is active in standards development 
#    through the IEEE PES and Standards Society and through IEC TC57.
#    
#    This is his blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rlc.vlinder.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: blytkerchan
github_username:  blytkerchan

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

excerpt_separator: <!--more-->
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
