name: Deploy

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Webpack"]
    types: ["completed"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: get Run ID
        id: get-run-id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_ID=$(gh run list --json  databaseId --workflow webpack.yml --repo ${{ github.repository }}  --limit 1 -q '.[0].databaseId')
          echo run-id=$(echo ${RUN_ID}) >> $GITHUB_OUTPUT

      - name: get Run ID
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download ${{ steps.get-run-id.outputs.run-id }} --repo ${{ github.repository }}
          cp serverless-config/serverless.yml serverless.yml
          mv site build

      - name: Display structure of downloaded files
        run: ls -R

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up serverless
        run: |
          npm i -g serverless
          serverless plugin install -n serverless-s3-sync
