name: NCC

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          mkdir -p build
          npm i -g @vercel/ncc
          npm install
          ncc build -o handlers/ src/handlers/index.js

      - name: publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambdas
          path: build
